palpiteCarla = [
    [
        "Catar",
        1,
        3,
        "Equador",
        "Away"
    ],
    [
        "Senegal",
        1,
        3,
        "Holanda",
        "Away"
    ],
    [
        "Catar",
        1,
        1,
        "Senegal",
        "Empate"
    ],
    [
        "Holanda",
        2,
        2,
        "Equador",
        "Empate"
    ],
    [
        "Equador",
        2,
        1,
        "Senegal",
        "Home"
    ],
    [
        "Holanda",
        3,
        1,
        "Catar",
        "Home"
    ],
    [
        "Inglaterra",
        3,
        0,
        "Irã",
        "Home"
    ],
    [
        "Gales",
        1,
        1,
        "Estados Unidos",
        "Empate"
    ],
    [
        "Gales",
        1,
        2,
        "Irã",
        "Away"
    ],
    [
        "Inglaterra",
        3,
        0,
        "Estados Unidos",
        "Home"
    ],
    [
        "Irã",
        1,
        2,
        "Estados Unidos",
        "Away"
    ],
    [
        "Gales",
        1,
        2,
        "Inglaterra",
        "Away"
    ],
    [
        "Argentina",
        3,
        0,
        "Arábia Saudita",
        "Home"
    ],
    [
        "México",
        3,
        2,
        "Polônia",
        "Home"
    ],
    [
        "Polônia",
        2,
        0,
        "Arábia Saudita",
        "Home"
    ],
    [
        "Argentina",
        1,
        1,
        "México",
        "Empate"
    ],
    [
        "Polônia",
        2,
        2,
        "Argentina",
        "Empate"
    ],
    [
        "Arábia Saudita",
        0,
        1,
        "México",
        "Away"
    ],
    [
        "Dinamarca",
        2,
        0,
        "Tunísia",
        "Home"
    ],
    [
        "França",
        3,
        1,
        "Austrália",
        "Home"
    ],
    [
        "Tunísia",
        1,
        1,
        "Austrália",
        "Empate"
    ],
    [
        "França",
        2,
        0,
        "Dinamarca",
        "Home"
    ],
    [
        "Tunísia",
        0,
        4,
        "França",
        "Away"
    ],
    [
        "Austrália",
        2,
        3,
        "Dinamarca",
        "Away"
    ],
    [
        "Alemanha",
        2,
        2,
        "Japão",
        "Empate"
    ],
    [
        "Espanha",
        3,
        2,
        "Costa Rica",
        "Home"
    ],
    [
        "Japão",
        2,
        2,
        "Costa Rica",
        "Empate"
    ],
    [
        "Espanha",
        2,
        3,
        "Alemanha",
        "Away"
    ],
    [
        "Japão",
        2,
        2,
        "Espanha",
        "Empate"
    ],
    [
        "Costa Rica",
        0,
        3,
        "Alemanha",
        "Away"
    ],
    [
        "Marrocos",
        1,
        2,
        "Croácia",
        "Away"
    ],
    [
        "Bélgica",
        1,
        1,
        "Canadá",
        "Empate"
    ],
    [
        "Bélgica",
        1,
        2,
        "Marrocos",
        "Away"
    ],
    [
        "Croácia",
        1,
        1,
        "Canadá",
        "Empate"
    ],
    [
        "Canadá",
        0,
        0,
        "Marrocos",
        "Empate"
    ],
    [
        "Croácia",
        0,
        1,
        "Bélgica",
        "Away"
    ],
    [
        "Suíça",
        1,
        2,
        "Camarões",
        "Away"
    ],
    [
        "Brasil",
        4,
        0,
        "Sérvia",
        "Home"
    ],
    [
        "Camarões",
        1,
        0,
        "Sérvia",
        "Home"
    ],
    [
        "Brasil",
        2,
        1,
        "Suíça",
        "Home"
    ],
    [
        "Sérvia",
        0,
        0,
        "Suíça",
        "Empate"
    ],
    [
        "Camarões",
        1,
        3,
        "Brasil",
        "Away"
    ],
    [
        "Uruguai",
        2,
        0,
        "Coreia do Sul",
        "Home"
    ],
    [
        "Portugal",
        3,
        0,
        "Gana",
        "Home"
    ],
    [
        "Coreia do Sul",
        1,
        1,
        "Gana",
        "Empate"
    ],
    [
        "Portugal",
        2,
        0,
        "Uruguai",
        "Home"
    ],
    [
        "Coreia do Sul",
        0,
        3,
        "Portugal",
        "Away"
    ],
    [
        "Gana",
        0,
        2,
        "Uruguai",
        "Away"
    ]
    ],
    palpiteJoao = [
        [
            "Catar",
            0,
            1,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            0,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            1,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            0,
            1,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            2,
            0,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            0,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            2,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            2,
            1,
            "Austrália",
            "Home"
        ],
        [
            "França",
            2,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            3,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            0,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            1,
            2,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            2,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            0,
            1,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            2,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            1,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            0,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            1,
            "Gana",
            "Away"
        ],
        [
            "Portugal",
            2,
            1,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteLeone = [
        [
            "Catar",
            1,
            2,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            0,
            3,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            4,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            1,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            0,
            0,
            "Irã",
            "Empate"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            1,
            "Inglaterra",
            "Empate"
        ],
        [
            "Argentina",
            4,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            2,
            "Polônia",
            "Away"
        ],
        [
            "Polônia",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            3,
            0,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            1,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            3,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            2,
            1,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            1,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            1,
            2,
            "Dinamarca",
            "Away"
        ],
        [
            "Tunísia",
            0,
            3,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            2,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            2,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            3,
            1,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            1,
            "Costa Rica",
            "Empate"
        ],
        [
            "Espanha",
            2,
            0,
            "Alemanha",
            "Home"
        ],
        [
            "Japão",
            0,
            1,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            1,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            3,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            2,
            "Marrocos",
            "Away"
        ],
        [
            "Croácia",
            1,
            1,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            1,
            1,
            "Camarões",
            "Empate"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            2,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            3,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            0,
            1,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            1,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            1,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            2,
            "Gana",
            "Away"
        ],
        [
            "Portugal",
            2,
            0,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            3,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            1,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteThalita = [
        [
            "Catar",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            3,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            3,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            1,
            "Irã",
            "Empate"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            0,
            1,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            4,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            0,
            1,
            "Polônia",
            "Away"
        ],
        [
            "Polônia",
            1,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            3,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            1,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            2,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            3,
            1,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            1,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            2,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            2,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Alemanha",
            2,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            0,
            0,
            "Costa Rica",
            "Empate"
        ],
        [
            "Espanha",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            1,
            3,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            3,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            1,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            1,
            "Canadá",
            "Empate"
        ],
        [
            "Canadá",
            2,
            1,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            2,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            1,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            1,
            "Sérvia",
            "Empate"
        ],
        [
            "Brasil",
            2,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            2,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            0,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            1,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            1,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            3,
            1,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            1,
            1,
            "Uruguai",
            "Empate"
        ]
    ]
    palpiteDanilo = [
        [
            "Catar",
            0,
            2,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            0,
            1,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            0,
            2,
            "Equador",
            "Away"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            3,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Gales",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            1,
            0,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            2,
            2,
            "Arábia Saudita",
            "Empate"
        ],
        [
            "Argentina",
            3,
            2,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            1,
            3,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            3,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "Austrália",
            "Away"
        ],
        [
            "França",
            3,
            1,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            0,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            2,
            1,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            3,
            2,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            3,
            2,
            "Alemanha",
            "Home"
        ],
        [
            "Japão",
            0,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            3,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            3,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            4,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            3,
            1,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            2,
            "Marrocos",
            "Away"
        ],
        [
            "Croácia",
            1,
            2,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            1,
            1,
            "Camarões",
            "Empate"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Brasil",
            1,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            2,
            2,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            1,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            3,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            2,
            2,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            2,
            3,
            "Uruguai",
            "Away"
        ],
        [
            "Coreia do Sul",
            1,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            2,
            1,
            "Uruguai",
            "Home"
        ]
    ]
    palpiteRafael = [
        [
            "Catar",
            1,
            2,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            0,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            2,
            1,
            "Senegal",
            "Home"
        ],
        [
            "Holanda",
            5,
            1,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            2,
            2,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            0,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            4,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            1,
            "Polônia",
            "Empate"
        ],
        [
            "Polônia",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            3,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            1,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            3,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            2,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            0,
            0,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Tunísia",
            0,
            1,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            3,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            3,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            5,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            3,
            1,
            "Alemanha",
            "Home"
        ],
        [
            "Japão",
            1,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            1,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            3,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            3,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            2,
            "Marrocos",
            "Away"
        ],
        [
            "Croácia",
            1,
            1,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            1,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            4,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            3,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            1,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            0,
            2,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            1,
            1,
            "Gana",
            "Empate"
        ],
        [
            "Coreia do Sul",
            1,
            2,
            "Gana",
            "Away"
        ],
        [
            "Portugal",
            1,
            1,
            "Uruguai",
            "Empate"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            2,
            2,
            "Uruguai",
            "Empate"
        ]
    ]
    palpiteMateus = [
        [
            "Catar",
            1,
            2,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            0,
            3,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            2,
            1,
            "Senegal",
            "Home"
        ],
        [
            "Holanda",
            2,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            1,
            2,
            "Irã",
            "Away"
        ],
        [
            "Inglaterra",
            2,
            0,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            1,
            0,
            "Estados Unidos",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            2,
            1,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            3,
            1,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            1,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            2,
            1,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            0,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            0,
            2,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            2,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            2,
            "Costa Rica",
            "Away"
        ],
        [
            "Espanha",
            2,
            1,
            "Alemanha",
            "Home"
        ],
        [
            "Japão",
            1,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            3,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            1,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            2,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            2,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            1,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            2,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            2,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            0,
            1,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            0,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            1,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            3,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            2,
            1,
            "Gana",
            "Home"
        ],
        [
            "Portugal",
            2,
            1,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteNilton = [
        [
            "Catar",
            1,
            3,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            1,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            3,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            1,
            "Irã",
            "Empate"
        ],
        [
            "Inglaterra",
            2,
            2,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Irã",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Gales",
            1,
            3,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            4,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            2,
            "Polônia",
            "Away"
        ],
        [
            "Polônia",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            3,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            3,
            1,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            3,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            2,
            1,
            "Austrália",
            "Home"
        ],
        [
            "França",
            2,
            2,
            "Dinamarca",
            "Empate"
        ],
        [
            "Tunísia",
            1,
            3,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            3,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            2,
            1,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            4,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            2,
            1,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            2,
            2,
            "Alemanha",
            "Empate"
        ],
        [
            "Japão",
            1,
            3,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            3,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            3,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            3,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            3,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            2,
            2,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            2,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            3,
            1,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            2,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            2,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            2,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            0,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            1,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            3,
            1,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            2,
            2,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            2,
            1,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            3,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteGeraldo = [
        [
            "Catar",
            0,
            3,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            1,
            1,
            "Equador",
            "Empate"
        ],
        [
            "Equador",
            2,
            1,
            "Senegal",
            "Home"
        ],
        [
            "Holanda",
            4,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Irã",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            0,
            0,
            "Inglaterra",
            "Empate"
        ],
        [
            "Argentina",
            2,
            1,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            1,
            1,
            "México",
            "Empate"
        ],
        [
            "Polônia",
            1,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            0,
            "México",
            "Empate"
        ],
        [
            "Dinamarca",
            4,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            4,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "Austrália",
            "Away"
        ],
        [
            "França",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Tunísia",
            1,
            4,
            "França",
            "Away"
        ],
        [
            "Austrália",
            0,
            2,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            1,
            1,
            "Japão",
            "Empate"
        ],
        [
            "Espanha",
            2,
            2,
            "Costa Rica",
            "Empate"
        ],
        [
            "Japão",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            0,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            1,
            0,
            "Espanha",
            "Home"
        ],
        [
            "Costa Rica",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            4,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            1,
            1,
            "Canadá",
            "Empate"
        ],
        [
            "Bélgica",
            3,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            0,
            0,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            1,
            1,
            "Camarões",
            "Empate"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            2,
            1,
            "Sérvia",
            "Home"
        ],
        [
            "Brasil",
            3,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            0,
            0,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            1,
            2,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            1,
            1,
            "Gana",
            "Empate"
        ],
        [
            "Coreia do Sul",
            0,
            0,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            1,
            1,
            "Uruguai",
            "Empate"
        ],
        [
            "Coreia do Sul",
            2,
            1,
            "Portugal",
            "Home"
        ],
        [
            "Gana",
            2,
            1,
            "Uruguai",
            "Home"
        ]
    ]
    palpiteGabriel =[
        [
            "Catar",
            0,
            1,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            1,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            3,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            1,
            1,
            "Irã",
            "Empate"
        ],
        [
            "Inglaterra",
            3,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            2,
            "Polônia",
            "Away"
        ],
        [
            "Polônia",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            0,
            "México",
            "Home"
        ],
        [
            "Polônia",
            2,
            3,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            1,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            2,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            1,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            0,
            "Austrália",
            "Home"
        ],
        [
            "França",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Tunísia",
            0,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            0,
            3,
            "Dinamarca",
            "Away"
        ],
        [
            "Alemanha",
            1,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            1,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            1,
            "Costa Rica",
            "Empate"
        ],
        [
            "Espanha",
            2,
            2,
            "Alemanha",
            "Empate"
        ],
        [
            "Japão",
            1,
            3,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            2,
            2,
            "Alemanha",
            "Empate"
        ],
        [
            "Marrocos",
            0,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            3,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            1,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            2,
            1,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            1,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            0,
            2,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            2,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            1,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            1,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            2,
            1,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            1,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            1,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            2,
            2,
            "Uruguai",
            "Empate"
        ],
        [
            "Coreia do Sul",
            0,
            1,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            1,
            1,
            "Uruguai",
            "Empate"
        ]
    ]
    palpiteMicaele =[
        [
            "Catar",
            1,
            1,
            "Equador",
            "Empate"
        ],
        [
            "Senegal",
            0,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            2,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            0,
            1,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            1,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            1,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            0,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            1,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            3,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            2,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            3,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            2,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            0,
            2,
            "Austrália",
            "Away"
        ],
        [
            "França",
            3,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            0,
            0,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            4,
            1,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            3,
            1,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            0,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            1,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            3,
            1,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            1,
            2,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            1,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            3,
            1,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            1,
            "Sérvia",
            "Empate"
        ],
        [
            "Brasil",
            2,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            1,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            0,
            3,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            3,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            3,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            1,
            "Gana",
            "Away"
        ],
        [
            "Portugal",
            1,
            1,
            "Uruguai",
            "Empate"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            1,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteLeonardo = [
        [
            "Catar",
            1,
            0,
            "Equador",
            "Home"
        ],
        [
            "Senegal",
            0,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            1,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            0,
            "Senegal",
            "Home"
        ],
        [
            "Holanda",
            1,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            1,
            "Estados Unidos",
            "Empate"
        ],
        [
            "Gales",
            1,
            0,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            1,
            "Inglaterra",
            "Empate"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            1,
            0,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            1,
            1,
            "Argentina",
            "Empate"
        ],
        [
            "Arábia Saudita",
            0,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            3,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            0,
            "Austrália",
            "Home"
        ],
        [
            "França",
            2,
            1,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            0,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            2,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            0,
            1,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            0,
            3,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            1,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            1,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            3,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            2,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            3,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            0,
            2,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            1,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            0,
            1,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            3,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            2,
            2,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            1,
            4,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            1,
            1,
            "Coreia do Sul",
            "Empate"
        ],
        [
            "Portugal",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            1,
            0,
            "Gana",
            "Home"
        ],
        [
            "Portugal",
            1,
            0,
            "Uruguai",
            "Home"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteJanio =[
        [
            "Catar",
            1,
            0,
            "Equador",
            "Home"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            0,
            3,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            1,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            0,
            0,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            5,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            1,
            "Irã",
            "Empate"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            0,
            1,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            1,
            2,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            2,
            "Polônia",
            "Empate"
        ],
        [
            "Polônia",
            1,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            0,
            0,
            "México",
            "Empate"
        ],
        [
            "Polônia",
            1,
            1,
            "Argentina",
            "Empate"
        ],
        [
            "Arábia Saudita",
            0,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            0,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            1,
            1,
            "Austrália",
            "Empate"
        ],
        [
            "Tunísia",
            0,
            1,
            "Austrália",
            "Away"
        ],
        [
            "França",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Tunísia",
            0,
            3,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Alemanha",
            2,
            1,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            3,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            2,
            2,
            "Alemanha",
            "Empate"
        ],
        [
            "Japão",
            0,
            2,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            3,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            1,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            1,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            0,
            1,
            "Marrocos",
            "Away"
        ],
        [
            "Croácia",
            0,
            0,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            0,
            1,
            "Camarões",
            "Away"
        ],
        [
            "Brasil",
            3,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Brasil",
            1,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            0,
            1,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            1,
            2,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            1,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            0,
            0,
            "Gana",
            "Empate"
        ],
        [
            "Coreia do Sul",
            1,
            1,
            "Gana",
            "Empate"
        ],
        [
            "Portugal",
            0,
            1,
            "Uruguai",
            "Away"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            2,
            "Uruguai",
            "Away"
        ]
    ]
    palpiteVitor =[
        [
            "Catar",
            1,
            2,
            "Equador",
            "Away"
        ],
        [
            "Senegal",
            1,
            1,
            "Holanda",
            "Empate"
        ],
        [
            "Catar",
            0,
            2,
            "Senegal",
            "Away"
        ],
        [
            "Holanda",
            2,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            2,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            1,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            2,
            0,
            "Estados Unidos",
            "Home"
        ],
        [
            "Gales",
            2,
            1,
            "Irã",
            "Home"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Gales",
            1,
            0,
            "Inglaterra",
            "Home"
        ],
        [
            "Argentina",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            1,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            3,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            2,
            0,
            "México",
            "Home"
        ],
        [
            "Polônia",
            1,
            3,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            1,
            2,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            2,
            1,
            "Tunísia",
            "Home"
        ],
        [
            "França",
            4,
            1,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            2,
            2,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            3,
            2,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            1,
            2,
            "França",
            "Away"
        ],
        [
            "Austrália",
            0,
            0,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            3,
            1,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            2,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            1,
            1,
            "Espanha",
            "Empate"
        ],
        [
            "Costa Rica",
            0,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            2,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            4,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            3,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            2,
            1,
            "Canadá",
            "Home"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            1,
            3,
            "Bélgica",
            "Away"
        ],
        [
            "Suíça",
            1,
            1,
            "Camarões",
            "Empate"
        ],
        [
            "Brasil",
            5,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            2,
            "Sérvia",
            "Away"
        ],
        [
            "Brasil",
            3,
            1,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            2,
            2,
            "Suíça",
            "Empate"
        ],
        [
            "Camarões",
            1,
            4,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            1,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            2,
            1,
            "Gana",
            "Home"
        ],
        [
            "Portugal",
            0,
            2,
            "Uruguai",
            "Away"
        ],
        [
            "Coreia do Sul",
            1,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            1,
            1,
            "Uruguai",
            "Empate"
        ]
    ]
    palpiteReginaldo = [
        [
            "Catar",
            1,
            1,
            "Equador",
            "Empate"
        ],
        [
            "Senegal",
            1,
            2,
            "Holanda",
            "Away"
        ],
        [
            "Catar",
            1,
            1,
            "Senegal",
            "Empate"
        ],
        [
            "Holanda",
            2,
            0,
            "Equador",
            "Home"
        ],
        [
            "Equador",
            2,
            1,
            "Senegal",
            "Home"
        ],
        [
            "Holanda",
            1,
            0,
            "Catar",
            "Home"
        ],
        [
            "Inglaterra",
            3,
            0,
            "Irã",
            "Home"
        ],
        [
            "Gales",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            0,
            1,
            "Irã",
            "Away"
        ],
        [
            "Inglaterra",
            2,
            1,
            "Estados Unidos",
            "Home"
        ],
        [
            "Irã",
            1,
            2,
            "Estados Unidos",
            "Away"
        ],
        [
            "Gales",
            0,
            4,
            "Inglaterra",
            "Away"
        ],
        [
            "Argentina",
            2,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "México",
            2,
            1,
            "Polônia",
            "Home"
        ],
        [
            "Polônia",
            1,
            0,
            "Arábia Saudita",
            "Home"
        ],
        [
            "Argentina",
            3,
            1,
            "México",
            "Home"
        ],
        [
            "Polônia",
            0,
            3,
            "Argentina",
            "Away"
        ],
        [
            "Arábia Saudita",
            0,
            1,
            "México",
            "Away"
        ],
        [
            "Dinamarca",
            1,
            1,
            "Tunísia",
            "Empate"
        ],
        [
            "França",
            2,
            0,
            "Austrália",
            "Home"
        ],
        [
            "Tunísia",
            1,
            1,
            "Austrália",
            "Empate"
        ],
        [
            "França",
            2,
            0,
            "Dinamarca",
            "Home"
        ],
        [
            "Tunísia",
            0,
            3,
            "França",
            "Away"
        ],
        [
            "Austrália",
            1,
            1,
            "Dinamarca",
            "Empate"
        ],
        [
            "Alemanha",
            2,
            0,
            "Japão",
            "Home"
        ],
        [
            "Espanha",
            3,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Japão",
            1,
            0,
            "Costa Rica",
            "Home"
        ],
        [
            "Espanha",
            1,
            2,
            "Alemanha",
            "Away"
        ],
        [
            "Japão",
            0,
            3,
            "Espanha",
            "Away"
        ],
        [
            "Costa Rica",
            0,
            4,
            "Alemanha",
            "Away"
        ],
        [
            "Marrocos",
            0,
            1,
            "Croácia",
            "Away"
        ],
        [
            "Bélgica",
            2,
            0,
            "Canadá",
            "Home"
        ],
        [
            "Bélgica",
            1,
            0,
            "Marrocos",
            "Home"
        ],
        [
            "Croácia",
            1,
            1,
            "Canadá",
            "Empate"
        ],
        [
            "Canadá",
            1,
            1,
            "Marrocos",
            "Empate"
        ],
        [
            "Croácia",
            0,
            0,
            "Bélgica",
            "Empate"
        ],
        [
            "Suíça",
            1,
            0,
            "Camarões",
            "Home"
        ],
        [
            "Brasil",
            2,
            0,
            "Sérvia",
            "Home"
        ],
        [
            "Camarões",
            1,
            1,
            "Sérvia",
            "Empate"
        ],
        [
            "Brasil",
            3,
            0,
            "Suíça",
            "Home"
        ],
        [
            "Sérvia",
            1,
            2,
            "Suíça",
            "Away"
        ],
        [
            "Camarões",
            0,
            4,
            "Brasil",
            "Away"
        ],
        [
            "Uruguai",
            1,
            0,
            "Coreia do Sul",
            "Home"
        ],
        [
            "Portugal",
            1,
            0,
            "Gana",
            "Home"
        ],
        [
            "Coreia do Sul",
            2,
            0,
            "Gana",
            "Home"
        ],
        [
            "Portugal",
            0,
            1,
            "Uruguai",
            "Away"
        ],
        [
            "Coreia do Sul",
            0,
            2,
            "Portugal",
            "Away"
        ],
        [
            "Gana",
            0,
            1,
            "Uruguai",
            "Away"
        ]
    ]
    var ids = new Map();
    ids.set("CARLA/CARLOS/ANA", 0);
    ids.set("JOAO", 1);
    ids.set("LEONE",2);
    ids.set("GABRIELA/THALITA", 3);
    ids.set("DANILO", 4);
    ids.set("RAFAEL", 5);
    ids.set("MATEUS",6);
    ids.set("NILTON", 7);
    ids.set("GERALDO", 8);
    ids.set("GABRIEL", 9);
    ids.set("MICAELE", 10);
    ids.set("LEONARDO", 11);
    ids.set("JANIO", 12); 
    ids.set("VITOR", 13);
    ids.set("REGINALDO", 14);
 

    palpites = [palpiteCarla,
        palpiteJoao,
        palpiteLeone,
        palpiteThalita,
        palpiteDanilo,
        palpiteRafael,
        palpiteMateus,
        palpiteNilton,
        palpiteGeraldo,
        palpiteGabriel,
        palpiteMicaele,
        palpiteLeonardo,
        palpiteJanio,
        palpiteVitor,
        palpiteReginaldo
    ]
   const input = document.getElementById('input')
   const gabarito = document.getElementById('gabarito')
 
   var jogos = [0,1,6,7,12,13,18,19,24,25,30,31,36,37,42,43,8,2,3]
   var rodada = new Set();
   rodada.add(8)
   rodada.add(2)
   rodada.add(3)
//    rodada.add(9)


   var jogosReal= [[0,2],[0,2],[6,2],[1,1],[1,2],[0,0],[0,0],[4,1],[1,2],[7,0],[0,0],[1,0],[1,0],[2,0],[0,0],[3,2],[0,2],[1,3],[1,1]]
 var totalRodada = 0;
   var players = new Map();
   players.set("JOAO", [0,0]);
   players.set("LEONE", [0,0]);
   players.set("RAFAEL",[0,0]);
   players.set("VITOR", [0,0]);
   players.set("MATEUS", [0,0]);
   players.set("NILTON", [0,0]);
   players.set("GERALDO", [0,0]);
   players.set("GABRIEL", [0,0]);
   players.set("REGINALDO", [0,0]);
   players.set("MICAELE", [0,0]);
   players.set("LEONARDO", [0,0]);
   players.set("JANIO", [0,0]);
   players.set("DANILO", [0,0]);
   players.set("CARLA/CARLOS/ANA", [0,0]);
   players.set("GABRIELA/THALITA", [0,0]);
 
 
   players.forEach(function(value, key) {
    j=0;
    indice = ids.get(key)

    jogosReal.forEach(real => {
    
        
    palpiteHome =    palpites[indice][jogos[j]][1]
    palpiteAway =    palpites[indice][jogos[j]][2]

     empatePlayer =palpiteHome == palpites[indice][jogos[j]][2];
     empateReal = real[1] == real[0];
 
     if(!empatePlayer){
       vencedorPlayer = palpites[indice][jogos[j]][1] > palpiteAway ? 'H' : 'A';
     }else{
       vencedorPlayer = '-1';
     }
 

     if(!empateReal){
        vencedorReal = real[0] > real[1] ? 'H' : 'A';
     }else{
        vencedorPlayer = '-2';

     }
 
     if(palpiteHome==real[0] && palpiteAway ==real[1]){
        soma = 25;
     }else if (vencedorPlayer == vencedorReal ){
       if(vencedorReal == 'H'){
         if(palpiteHome == real[0]){
           soma = 18;
         }else if(Math.abs( palpiteHome - palpiteAway) == Math.abs( real[0] - real[1])){
            soma = 15;
         }else if(palpiteAway == real[1]){
            soma = 12;
         }else{
            soma = 10;
         }
       }else{
         if(palpiteAway == real[1]){
            soma = 18;
         }else if(Math.abs( palpiteHome- palpiteAway) == Math.abs( real[0] - real[1])){
            soma = 15;
         }else if(palpiteHome == real[0]){
            soma = 12;
         }else{
            soma = 10;
         }
       }
     }else if (empatePlayer ){
 
       if(empateReal ){
        soma = 15;
       }else{
        soma = 4;
 
       }
 
     }
     value[0] = value[0] + soma;

     if(rodada.has(jogos[j])){
        totalRodada = totalRodada + soma;
     }
     value[1] = totalRodada; 

     j++;
     players.set(key,value)
     soma=0;
    })
    totalRodada = 0;
})
 
   var ordenado = new Map([...players.entries()].sort((a, b) => b[1][0] - a[1][0]));
 trs =    $('td.player')
 trs2 =    $('td.pontuacao')
 trs3 =    $('td.pontuacao-rodada')
 
 
 i = 0;
 ordenado.forEach(function(value, key) {
     trs.get(i).innerHTML = key;
     trs2.get(i).innerHTML = value[0];
     trs3.get(i).innerHTML = "+"+value[1];
     i++;
 })
 
   const AInit = 3
   const AFim = 8
   const BInit = 11
   const BFim = 16
   const CInit = 19
   const CFim = 24
   const DInit = 27
   const DFim = 32
   const EInit = 35
   const EFim = 40
   const FInit = 43
   const FFim = 48
   const GInit = 51
   const GFim = 56
   const HInit = 59
   const HFim = 64


   const timeHome = 3
   const placarHome = 5
   const placarAway = 7
   const timeAway = 9

    thTime1 = $('th.time1')[0]
    thTime2 = $('th.time2')[0]

    tdsTime1 = $('td.time1')
    tdsTime2 = $('td.time2')

    tdsNomes = $('table.jogos td.jogador-palpites')

    // inputNumJogo = $('#quantity');
    // inputNumJogo.addEventListener('change', (data) => {
    //     console.log(data)
    //   })
 // 6,7,1
 var jogo = 9
    thTime1.innerHTML = palpites[0][jogo][0]
    thTime2.innerHTML = palpites[0][jogo][3]

    ids.forEach(function(value, key) {
        if(palpites[value][jogo][1] < palpites[value][jogo][2]){
            tdsTime1[value].classList.add("vermelho")
            tdsTime2[value].classList.add("verde")

        }else if(palpites[value][jogo][1] > palpites[value][jogo][2]){
            tdsTime2[value].classList.add("vermelho")
            tdsTime1[value].classList.add("verde")
        }else{
            tdsTime2[value].classList.add("cinza")
            tdsTime1[value].classList.add("cinza")
        }
        tdsNomes[value].innerHTML = key;
        tdsTime1[value].innerHTML = palpites[value][jogo][1]
        tdsTime2[value].innerHTML = palpites[value][jogo][2]

    })

   const jogosGab = new Array(48)
   var jogoGabId = 0;
 
  for (i=0; i<48; i++){
   jogosGab[i] = new Array(5)
  }
 
 
   input.addEventListener('change', () => {
     readXlsxFile(input.files[0]).then((data) => {
       writeTabela(data)
     })
   })
 
   gabarito.addEventListener('change', () => {
     readXlsxFile(gabarito.files[0]).then((data) => {
       writeTabelaGab(data)
     })
   })


 function writeTabela(readData) {
   escreveJogosPorGrupo(readData, AInit, AFim)
   escreveJogosPorGrupo(readData, BInit, BFim)
   escreveJogosPorGrupo(readData, CInit, CFim)
   escreveJogosPorGrupo(readData, DInit, DFim)
   escreveJogosPorGrupo(readData, EInit, EFim)
   escreveJogosPorGrupo(readData, FInit, FFim)
   escreveJogosPorGrupo(readData, GInit, GFim)
   escreveJogosPorGrupo(readData, HInit, HFim)
   console.log('___________________________')
   console.log(readData)

 }
 
 function writeTabelaGab(readData) {
   escreveJogosPorGrupoGab(readData, AInit, AFim)
   escreveJogosPorGrupoGab(readData, BInit, BFim)
   escreveJogosPorGrupoGab(readData, CInit, CFim)
   escreveJogosPorGrupoGab(readData, DInit, DFim)
   escreveJogosPorGrupoGab(readData, EInit, EFim)
   escreveJogosPorGrupoGab(readData, FInit, FFim)
   escreveJogosPorGrupoGab(readData, GInit, GFim)
   escreveJogosPorGrupoGab(readData, HInit, HFim)
   console.log(jogosGab)
 }
 
   function escreveJogosPorGrupo(readData, inicio, fim) {
     console.log('___________________________')
     for (i = inicio; i <= fim; i++) {
       console.log(readData[i][timeHome] + ' ' + verificaSeNulo(readData[i][placarHome]) + 
               ' x ' + verificaSeNulo(readData[i][placarAway]) + ' ' + readData[i][timeAway])
     }
   }
 
   function escreveJogosPorGrupoGab(readData, inicio, fim) {
     for (i = inicio; i<= fim; i++){
       jogosGab[jogoGabId][0] = readData[i][timeHome]
       jogosGab[jogoGabId][1] = verificaSeNulo(readData[i][placarHome])
       jogosGab[jogoGabId][2] = verificaSeNulo(readData[i][placarAway])
       jogosGab[jogoGabId][3] = readData[i][timeAway]
       jogosGab[jogoGabId][4] = getResultado(jogosGab[jogoGabId][1], jogosGab[jogoGabId][2])
       jogoGabId++
     }
   }
 
   function getResultado(placar1, placar2){
     if (placar1 > placar2){
       return 'Home'
     } else if (placar1 < placar2) {
       return 'Away'
     } else {
       return 'Empate'
     }
   }
 
   function verificaSeNulo(placar) {
     return placar==null ? 0 : placar
   }
 
 
 
 